version: "3"
services:
  postgres:
    image: postgres:14
#    image: postgres:13
    restart: always
    hostname: kong-database
    container_name: kong-database
    environment:
      POSTGRES_DB: "kong"
      POSTGRES_USER: "kong"
      POSTGRES_PASSWORD: "kong"
    ports:
      - "5432:5432"
    volumes:
      - "kong-db-data:/var/lib/postgresql/data"
  kong-bootstrap:
    image: kong/kong-gateway:3.2
#    image: kong:2.8.1
    hostname: kong-bootstrap
    container_name: kong-bootstrap
    depends_on:
      - postgres
    environment:
      KONG_DATABASE: "postgres"
      KONG_PG_HOST: "kong-database"
      KONG_PG_DATABASE: "kong"
      KONG_PG_USER: "kong"
      KONG_PG_PASSWORD: "kong"
    command: "kong migrations bootstrap"
    restart: 'on-failure'
    platform: linux/x86_64
  kong:
    image: kong/kong-gateway:3.2
#    image: kong:2.8.1
    restart: always
    hostname: kong
    container_name: kong
    depends_on:
      - kong-bootstrap
    environment:
      KONG_DATABASE: "postgres"
      KONG_PG_HOST: "kong-database"
      KONG_PG_DATABASE: "kong"
      KONG_PG_USER: "kong"
      KONG_PG_PASSWORD: "kong"
      KONG_PROXY_ACCESS_LOG: '/dev/stdout'
      KONG_ADMIN_ACCESS_LOG: '/dev/stdout'
      KONG_PROXY_ERROR_LOG: '/dev/stderr'
      KONG_ADMIN_ERROR_LOG: '/dev/stderr'
      KONG_ADMIN_LISTEN: "0.0.0.0:8001, 0.0.0.0:8444 ssl"
    command: "kong start"
    ports:
      - "8000:8000"
      - "8443:8443"
      - "8001:8001"
      - "8444:8444"
    platform: linux/x86_64
networks:
  default:
    name: kong-net
volumes:
  kong-db-data: